sudo: required

language: go

go:
    - 1.13.x

services:
    - docker

install:
    - go get -u golang.org/x/lint/golint
    - go install golang.org/x/lint/golint

script:
    - "bash check.sh"
    - CGO_ENABLED=0 go build .

after_success:
    - "bash cd.sh"

