language: go

go:
    - 1.10.x
    - 1.11.x

install:
    - go get -u golang.org/x/lint/golint
    - go install golang.org/x/lint/golint

script:
    - go get -t ./...
    - "bash check.sh"
    - go build .

